version: '3.1'

services:

    wordpress:
        build: 
            context: ./wordpress
        image: my_wordpress
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_PASSWORD: example
        volumes:
          - ./wordpress/src:/var/www/html

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
          - db_data:/var/lib/mysql

    adminer:
        image: adminer
        ports:
            - 5555:8080

volumes:
    db_data: